Use only manually Fedora test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -14,34 +14,103 @@ on:
   push:
     branches:
       - main
+  workflow_dispatch:
+    inputs:
+      debug:
+        default: false
+        description: Use Tmate session for debugging
+        type: boolean
+      job:
+        default: debian
+        description: CI job to run
+        options:
+          - alpine
+          - arch
+          - debian
+          - fedora
+          - freebsd
+          - macos
+          - package
+          - suse
+          - ubuntu
+          - windows
+        type: choice
+      platform:
+        default: amd64
+        description: Docker architecture platform
+        options:
+          - amd64
+          - arm64
+        type: choice
 
 jobs:
   fedora:
     name: Test bootstrapping software for Fedora Linux
     env:
       DOCKER_BUILD_SUMMARY: "false"
+    if: >-
+      ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'fedora' }}
     runs-on: ubuntu-24.04
     steps:
+      - name: Free disk space
+        uses: jlumbroso/free-disk-space@main
+        with:
+          tool-cache: true
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-      # - name: Build directly
-      #   run: |
-      #     docker build -f tests/integration/fedora.dockerfile .
       - name: Build Docker image
-        uses: docker/build-push-action@v6
+        run: >-
+          docker build --no-cache --build-arg test=true --file
+          tests/integration/fedora.dockerfile --tag
+          docker.io/scruffaluff/bootware:fedora --platform linux/${{
+          inputs.platform || 'amd64' }}
+      - name: Setup Tmate session if debug enabled
+        if: >-
+          ${{ always() && github.event_name == 'workflow_dispatch' &&
+          inputs.debug }}
+        timeout-minutes: 60
+        uses: mxschmitt/action-tmate@v3
+
+  freebsd:
+    name: Test bootstrapping software for FreeBSD
+    # Removed from default test suite until
+    # https://github.com/vmactions/freebsd-vm supports MacOS and CPU
+    # acceleration again to avoid action timeouts.
+    if: >-
+      ${{ github.event_name != 'workflow_dispatch' || inputs.job == 'freebsd' }}
+    runs-on: ubuntu-24.04
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Test installation, setup, and bootstrapping
+        env:
+          BOOTWARE_GITHUB_TOKEN: ${{ github.token }}
+        uses: vmactions/freebsd-vm@v1
         with:
-          build-args: |
-            tags=essential
-            test=true
-          context: .
-          file: tests/integration/fedora.dockerfile
-          platforms: linux/${{ inputs.platform || 'amd64' }}
-          push: false
-          tags: docker.io/scruffaluff/bootware:fedora
+          envs: BOOTWARE_GITHUB_TOKEN
+          prepare: |
+            sudo freebsd-update fetch
+            sudo freebsd-update install
+            pkg install --yes curl
+          release: "14.1"
+          # Audacity and Musescore tests are skipped in FreeBSD VM since they
+          # require a display connection. Python is skipped since Poetry fails
+          # during installation as 02/28/2025.
+          #
+          # TODO: Create nonadmin user for test since VLC cannot run as root.
+          run: |
+            set -eou pipefail
+            ./install.sh
+            ./bootware.sh setup
+            ./bootware.sh bootstrap --dev --no-passwd --retries 3 --skip python --tags desktop,extras
+            bash -c 'source $HOME/.bashrc && tests/integration/roles.test.ts --arch amd64 --skip audacity,musescore,python,vlc freebsd'
+          usesh: true
+      # To login into the FreeBSD VM from the MacOS runner, execute `ssh -t
+      # freebsd` and `cd /root/work/bootware/bootware`.
       - name: Setup Tmate session if debug enabled
         if: >-
           ${{ always() && github.event_name == 'workflow_dispatch' &&
